spring:
  datasource:
    url: jdbc:oracle:thin:@TESTDB.localdomain:1521/ORATECH
    username: oratechuser
    password: OraTech25
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
